# Generated by Django 3.2.25 on 2024-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_date', models.CharField(max_length=255)),
                ('deployment_name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ticket', models.CharField(max_length=50)),
                ('appname', models.CharField(max_length=255)),
                ('owner_value', models.CharField(max_length=255)),
                ('datacenter', models.CharField(max_length=50)),
                ('server_type_value', models.CharField(max_length=50)),
                ('deployment_count', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('os_value', models.CharField(max_length=50)),
                ('disk_size', models.IntegerField()),
                ('add_disks', models.BooleanField()),
                ('additional_disk_size', models.IntegerField()),
                ('mount_path', models.CharField(max_length=50)),
                ('cluster', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=50)),
                ('nfs_home', models.BooleanField()),
                ('join_centrify', models.BooleanField()),
                ('centrify_zone', models.CharField(max_length=50)),
                ('centrify_role', models.CharField(max_length=50)),
                ('install_patches', models.BooleanField()),
                ('status', models.CharField(default='spooled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
