# Generated by Django 3.2.25 on 2024-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='server_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
