# Generated by Django 3.2.25 on 2024-10-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20241010_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='additional_disk_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='centrify_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='centrify_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='mount_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
