# Generated by Django 3.2.25 on 2024-10-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20241010_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='full_hostnames',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
