# Generated by Django 3.2.25 on 2024-10-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_deployment_full_hostnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='full_hostnames',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
