# Generated by Django 3.2.25 on 2024-10-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_deployment_full_hostnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='centrify_role',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='centrify_zone',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='mount_path',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='os',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='owner',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='server_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
