# Generated by Django 3.2.25 on 2024-10-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20241011_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='centrify_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='centrify_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='mount_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
    ]
